alias: "Minimote: Office 3"
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    object_id: __9
    scene_id: 5
action:
  service: scene.turn_on
  entity_id: scene.bedside_steve_dim
