alias: "Minimote: Office 2"
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    object_id: __9
    scene_id: 3
action:
  service: light.turn_on
  entity_id:
    - light.linear_lb60z1_dimmable_led_light_bulb_level_2
    - light.linear_lb60z1_dimmable_led_light_bulb_level_3
