alias: "Minimote: Office 1 (Long)"
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    object_id: _
    scene_id: 2
action:
  service: scene.turn_on
  entity_id: scene.office_off
