alias: "Minimote: Office 2 (Long)"
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    object_id: __9
    scene_id: 4
action:
  service: light.turn_on
  entity_id: light.closet

