alias: "Minimote: Office 4"
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    object_id: _
    scene_id: 7
action:
  service: switch.toggle
  entity_id: switch.ge_12721_lighting_control_duplex_receptacle_switch_8_0

