alias: "Minimote: Office 3 (Long)"
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    object_id: _
    scene_id: 6
action:
  service: light.turn_off
  entity_id: light.bedside_steve
