alias: "Minimote: Office 2 (Long)"
trigger:
  platform: event
  event_type: zwave.scene_activated
  event_data:
    object_id: _
    scene_id: 4
action:
  service: light.toggle
  entity_id: light.linear_lb60z1_dimmable_led_light_bulb_level_2_0
