alias: "Air filter unless alone"
trigger:
  platform: event
  event_type: call_service
  event_data:
    service_data:
      entity_id: scene.office_on
    domain: scene
    service: turn_on
condition:
  condition: state
  entity_id: device_tracker.owntrackschristine_owntrackschristinesimmscloud
  state: home
action:
  service: switch.turn_on
  entity_id: switch.ge_12721_lighting_control_duplex_receptacle_switch
