alias: "Air filter unless alone"
trigger:
  platform: state
  entity_id: input_boolean.filter_maybe
  state: 'on'
condition:
  condition: state
  entity_id: device_tracker.christinephonehsd1nhcomcastnet
  state: home
action:
  service: switch.turn_on
  entity_id: switch.ge_12721_lighting_control_duplex_receptacle_switch_8
